### ISSUE TITLE
Map Component

### ISSUE THREAD

**Issue by Archish27** [reflexjs/reflexjs#103]
Is there a component which shows map based on address / location?
Map Component missing?

**Comment by arshad** [comment]
There's no map component out of the box. But you should be able to create one using `Iframe`.

See example: https://reflex-map.netlify.app/basic

Here's the `GoogleMap` component: https://github.com/arshad/reflex-map/blob/master/src/components/google-map.jsx

To use it on a page:

```mdx
---
title: Basic page
excerpt: This is basic text-only page.
---

import { GoogleMap } from "../../src/components/google-map"

<Container>

# Basic page

<GoogleMap
  address="The Painted Ladies, San Francisco"
  h="450"
  boxShadow="xl"
  rounded="lg"
/>

More content here
```
