### ISSUE TITLE
@reflexjs/ui vs reflexjs package

### ISSUE THREAD

**Issue by RishikeshDarandale** [reflexjs/reflexjs#130]
I see that recently `reflexjs` announced the support for `next.js`. Having said above, can you please describe how `reflexjs` package supported over `@reflexjs/ui` package?

Basically, I wanted to understand once `reflexjs` becomes `GA`, `@reflexjs/ui` gets deprecated? If no, then which one would be great to use with `next.js`? What would be maintainability of `ui` package?

**Comment by arshad** [comment]
Sure. We are going to deprecate `@reflexjs/ui` and `@reflexjs/components` in favor of `reflexjs`. A codemod will be available to migrate your existing components to `reflexjs`.

The biggest changes are:

- No more component import required. `Div`, `Img`, `H1` are replaced by JSX: `div`, `img` and `h1`.
- Presets, while still supported, will be replaced by a `theme.js` file that you can generate using `npx reflexjs`--preset base. (We think presets hide theme implementation and it makes it difficult for users to find where some tokens coming from.)

For new sites (Gatsby or Nextjs), choose `reflexjs`. We have starters you can use (or reference if you're building your own):

- **Gatsby**: https://github.com/reflexjs/reflexjs/tree/master/starters/gatsby-starter
- **Nextjs**: https://github.com/reflexjs/reflexjs/tree/master/starters/nextjs-starter

(We are working on Typescript starters as well). 

> What would be maintainability of ui package

`@reflexjs/ui` will get bug fixes but no new features.

The reflexjs.org site is a good reference if you are building a Nextjs + Reflexjs site: https://github.com/reflexjs/reflexjs/tree/master/sites/www-next

**Comment by RishikeshDarandale** [comment]
Thanks for the update @arshad !

> Presets, while still supported, will be replaced by a theme.js file that you can generate using npx reflexjs--preset base. (We think presets hide theme implementation and it makes it difficult for users to find where some tokens coming from.)

IMO, presets with theme support should be there same as `theme-ui`. So that with minimum changes one can get started, anyway we can use it like below:

```
import theme from '@some/theme-package'

export default {
  ...theme
};

```

> We are working on Typescript starters as well

What is the timeframe you guys are targeting?

**Comment by arshad** [comment]
> IMO, presets with theme support should be there same as theme-ui.

Yes. We are keeping the `preset` support.

> What is the timeframe you guys are targeting?

By the end of this week (we're very close).

**Comment by arshad** [comment]
@RishikeshDarandale The Typescript starters are up. 

- [Next.js](https://github.com/reflexjs/nextjs-starter)
- [Next.js (Typescript)](https://github.com/reflexjs/nextjs-starter-typescript)
- [Gatsby](https://github.com/reflexjs/gatsby-starter)
- [Gatsby (Typescript)](https://github.com/reflexjs/gatsby-starter-typescript)

**Comment by RishikeshDarandale** [comment]
@arshad , one more thing while using [blocks](https://reflexjs.org/blocks/cards-002), variants like `test.paragraph`, `text.sm`, `text.link` are missing. I took the updated package today, but still they are missing. Can you please update the base file? 

IMO, it would be be great if you update in `preset-base` package!

**Comment by arshad** [comment]
@RishikeshDarandale I'll take a look at it. Thanks for the heads up.
