### ISSUE TITLE
Cannot compile in `next.js` or `blitz.js` if using `<>`

### ISSUE THREAD

**Issue by rayandrews** [reflexjs/reflexjs#131]
Hi thanks for the library!

I want to use this library to create dashboard.

However, I found bug that is little annoying.
Fortunately it is actually fixable.

The `React.Fragment` can be written in `<>` form, however, the compilation will throw error at least for `next.js` and `blitz.js`.

How to reproduce:

Just put fragment in `<>` form everywhere (for easy reproduce put it in index page)

Here is the error using `reflexjs next typescript template`:

```
| import { Icon } from "reflexjs";
| export default function IndexPage() {
>   return jsx(Layout, null, jsx(, null, jsx("div", null, "Hello")), jsx(Hero, {
|     heading: "Build something amazing",
|     text: "Reiciendis quia totam esse. Dicta minus iusto quisquam doloribus temporibus.",
```

I actually find the solution by modifying the `reflexjs/babel` right from the `node_modules`

https://github.com/reflexjs/reflexjs/blob/master/packages/reflexjs/src/babel.ts#L17

```diff
export default (_, { ...options } = {}) => {
  return {
    plugins: [
      [
        pragmatic,
        {
          export: "jsx",
          module: "reflexjs",
          import: pragmaName,
        },
      ],
-     [jsx, { pragma: pragmaName, pragmaFrag: "", ...options }],
+     [jsx, { pragma: pragmaName, pragmaFrag: "React.Fragment", ...options }],
    ],
  }
}
```

I can confirm `emotion` uses the same solution in their babel plugin:

https://github.com/emotion-js/emotion/blob/master/packages/babel-preset-css-prop/src/index.js#L36

Want me to open PR for that?
Thank you in advance!

Best regards,
-- Ray

**Comment by arshad** [comment]
Woah. I'm definitely seeing this issue too. 

Can you create a PR please? If not, that's ok. I'll fix it later. 

Thank you for looking into this. Really appreciate it.

**Comment by rayandrews** [comment]
I have opened the PR at #132 

Thank you @arshad!
