### ISSUE TITLE
Migration guide or updated documentation?

### ISSUE THREAD

**Issue by rxdu** [reflexjs/reflexjs#133]
Hello, 

I'm a JS/Gatsby beginner trying to set up a personal site with reflexjs. I can see reflexjs provides a lot of functionalities and it's quite easy to get the starter up and running. 

But then I get lost for the next steps. It seems the legacy docs provide a lot more details than the current one but I'm not sure how to take advantage of those docs to work with the latest code. For example, starting from the starter, how could I add docs written in markdown? How can I add a "doc" page? Am I still supposed to follow readme in specific packages (such as https://github.com/reflexjs/reflexjs/tree/master/packages/gatsby-theme-doc)? 

I will keep reading gatsby and reflexjs docs and learn more about relevant topics. But I was wondering whether anyone here could give me some pointers to help me catch up faster.

Thank you,
rxdu

**Comment by arshad** [comment]
Hi @rxdu, the docs are still in the works and unfortunately this is taking a bit longer. 

But I'd be happy to help you. 
 
You can post your questions here and we can figure it out together.

**Comment by rxdu** [comment]
> Hi @rxdu, the docs are still in the works and unfortunately this is taking a bit longer.
> 
> But I'd be happy to help you.
> 
> You can post your questions here and we can figure it out together.

Thank you very much! As one of the first steps to customize the starter theme (gatsby-starter-typescript), I'm trying to change colors. Since 'color modes" is one of the highlighted features and I notice there is already "dark" defined in "theme.ts" but I failed to find the right place to activate this mode. Any suggestions?

**Comment by arshad** [comment]
Sure. You can define your theme colors as follows:

```js
module.exports = {
  colors: {
    text: "#111",
    background: "#fff",
    modes: {
      dark: {
        text: "#a0aec0",
        background: "#1a202c",
      },
      lemon: {
        background: "#4d908e",
        text: "#e9c46a"
      }
    }
  },
};
```

Then use the `useColorMode` hook to set the color mode.

See https://reflexjs.org/docs/theming/color-modes#setting-the-color-mode

I created a sandbox here with a color mode toggle: https://codesandbox.io/s/reflexjs-color-mode-toggle-qxp5f?file=/src/components/color-mode-toggle.tsx

![color-mode](https://user-images.githubusercontent.com/124599/102113559-9e5bf880-3e52-11eb-8233-ac0ff70ff687.gif)

**Comment by rxdu** [comment]
Thanks for the sample code and links. Missed the doc page for this topic, my bad. Will spend more time reading documentation before asking more questions like this one.

**Comment by rxdu** [comment]
I've managed to migrate my personal site from Jekyll to gatsby with your starter (BTW my site: https://rdu.im) and I found the discussion in issue #123 particularly helpful for my case. Still need to spend more time on JS and React/Gatsby to make more customizations. But I really want to thank you again for your help and your great work!

**Comment by arshad** [comment]
The site is looking really nice. Congrats on the launch @rxdu

**Comment by pipifix** [comment]
I would like to bump this issue.  A migration guide and getting rid of the legacy doc would be wonderful. Thanks for your work @arshad

**Comment by arshad** [comment]
@pipifix I just published the migration guide: https://reflexjs.org/docs/migrate

Note: I've tested this guide with the official legacy.reflexjs.org site and the base starter. Let me know if you find any issues.
