### ISSUE TITLE
Unable to open dropdown menu in developer mode (@Chrome)

### ISSUE THREAD

**Issue by benbehringer** [reflexjs/reflexjs#139]
Hi,

I have a dropdown menu, which works just fine until I enter developer mode on Chrome (i.e., the popup doesn't show up after hovering the parent element). Not sure whether this is a reflexjs issue or not ;)

Thanks
Ben

**Comment by arshad** [comment]
Can you help me reproduce this? Code snippet or a screenshot. Thank you

**Comment by benbehringer** [comment]
Actually it is not related to developer mode, but to the browser window width. As soon as it's not on full width (first breakpoint) the popup doesn't show up anymore. Any ideas?
Hamburger menu works as expected!

**Comment by benbehringer** [comment]
Okay, found the issue (cf. pull request https://github.com/reflexjs/reflexjs/pull/142)
