### ISSUE TITLE
Reflex site loads desktop version on mobile

### ISSUE THREAD

**Issue by mattmaker** [reflexjs/reflexjs#145]
I just finished a site using the latest version of Reflex and when I load it on mobile it shows the desktop version of the site.

The old legacy version worked just fine.

I checked lighthouse and it says the site is missing the `<meta name="viewport">` tag. 

I tried it on a fresh install of Reflex and got the same thing.

How can I fix this? Should I install `gatsby-plugin-react-helmet` ?

**Comment by arshad** [comment]
Did you figure this out? Are you using one of the starters?

**Comment by mattmaker** [comment]
I haven't figured it out yet. I'm using the Gatsby starter.

I was searching through closed issues to see if anyone had this happen before and noticed you said the meta tags package uses React Helmet.

I tried installing React Helmet and also tried the `@reflexjs/gatsby-plugin-metatags` plugin, but wasn't exactly sure what I was doing and ended up breaking things.

I think if I can just add React Helmet with a `<meta name="viewport">` tag, then it should fix the problem.

What do you think?

**Comment by arshad** [comment]
Let me see if I can reproduce this.

**Comment by arshad** [comment]
OK I think I know what's happening here. This is coming from `reflexjs`. 

`<meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no;" />`

The `content` attribute here is being treated as a style prop (the CSS [content](https://developer.mozilla.org/en-US/docs/Web/CSS/content) property). 

Looking into a fix (we probably need a blacklist of tags that should not be fed to the reflexjs JSX pragma - `<meta />` does not need styles).

This is an interesting bug. Thanks for reporting this 👍

**Comment by arshad** [comment]
From the [specs](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes), `content` attribute can only be used on `meta` tag.

I guess we can add a check for now.

**Comment by arshad** [comment]
I fixed it and tagged reflexjs 1.0.3.

Can you update and test?

Thank you

**Comment by mattmaker** [comment]
Thanks @arshad !! Works great now.

Also I'm not sure if I should open a new issue for this, but in the future if I want to add metatags for SEO purposes how would I go about doing that?

**Comment by arshad** [comment]
The `@reflexjs/gatsby-plugin-metatags` works best with `mdx`content and the other reflexjs plugins. 

If you're not using mdx, you can use https://www.gatsbyjs.com/plugins/gatsby-plugin-react-helmet/

**Comment by mattmaker** [comment]
So if I understand correctly, `@reflex/gatsby-plugin-metatags` would work best with the legacy version of Reflex, and `gatsby-plugin-react-helmet` for the regular version right?

Since the legacy version comes with the metatags plugin, should I just shadow the `metatags.js` file?
