### ISSUE TITLE
variant prop ignored when passed to custom component

### ISSUE THREAD

**Issue by ftes** [reflexjs/reflexjs#149]
# Input
```js
const MyComponent = ({ children, ...props }) =>
  <div {...props}>{children}</div>

const CompWithStyleProp = () =>
  <MyComponent color="red">Works: comp with style prop</MyComponent>

const DivWithVariant = () =>
  <div variant="heading.h3">Works: div with variant</div>

const CompWithVariant = () =>
  <MyComponent variant="heading.h3">Doesn't work: comp with variant</MyComponent>

// render
export default () => (
  <div>
    <CompWithStyleProp/>
    <DivWithVariant/>
    <CompWithVariant/>
  </div>
)
```

# Output
![image](https://user-images.githubusercontent.com/2614732/110604056-f66f7600-8187-11eb-92e8-60ede945cfd3.png)

# Expected output
I expect the third line (`CompWithVariant`) to be rendered with the `heading.h3` variant.

Passing style props to a custom component works as expected.
Passing a variant prop to a regular DOM tag (`div`) works as expected.
Passing a variant prop to a custom component does not cause the style to be applied to the rendered output.

**Comment by arshad** [comment]
I've been able to reproduce this. Looking into it.

Thanks for filing this bug.

**Comment by arshad** [comment]
@ftes Is this a blocker? Just so I can set priority. Thank you.

**Comment by ftes** [comment]
Not a blocker for me.

I can work around it by adding the variant inside the custom component for now (the variant is static, always the same, for my use case).

**Comment by arshad** [comment]
This is now fixed and tagged under the 1.1.0 release.

I looked at this the other day and couldn't figure it out. Gave it another go today and took 30min to fix. 

Programming is weird :D

**Comment by arshad** [comment]
Here's the test just in case

https://github.com/reflexjs/reflexjs/blob/e444c860a57c2499c372c65e65b1fe0c49890d02/packages/reflexjs/test/index.test.js#L265-L284

**Comment by ftes** [comment]
Neat, thanks! I will try this out in the next days.
