### ISSUE TITLE
nav burger svg not showing (on gatsbyjs)

### ISSUE THREAD

**Issue by deeplinked** [reflexjs/reflexjs#183]
installed as gatsby starter and copied the code for header from blocks library, nav burger svg not showing. 

![2021-08-09 11_33_00-Window](https://user-images.githubusercontent.com/62131140/128665586-39cbd1cf-5a05-4322-9c36-5416218e709e.png)

**Comment by arshad** [comment]
Hmm can you inspect and confirm if the svg is in there?

**Comment by deeplinked** [comment]
no svg inside button
![2021-08-09 13_20_02-Window](https://user-images.githubusercontent.com/62131140/128674634-55bcc0f8-e4de-499c-bc04-623e048a662f.png)

**Comment by arshad** [comment]
I see. You probably need to add the icon your theme file `src/gatsby-plugin-reflexjs/index.js`.

```js
...
icons: {
   "menu-alt": `<svg viewBox="0 0 24 24"  fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 12h18M3 6h18M3 18h18"/></svg>`,
  },
...
```

**Comment by deeplinked** [comment]
after adding this got it, thanks a lot :)
