### ISSUE TITLE
Do i have to install any plugin to make images to work in reflex? (Gatsby js)

### ISSUE THREAD

**Issue by deeplinked** [reflexjs/reflexjs#194]
images are not loading.

![2021-09-20 11_03_44-Window](https://user-images.githubusercontent.com/62131140/133960607-b6eb34b6-c7ad-4943-b75b-89692380a4c4.png)

sorry if this seems to be a dumb question, new to react finding it a bit hard to learn gatsby.

![2021-09-20 10_54_12-Window](https://user-images.githubusercontent.com/62131140/133960019-ef36fded-f91b-46cc-96a3-ce7a487cadd2.png)
![2021-09-20 10_57_05-Window](https://user-images.githubusercontent.com/62131140/133960119-2ad5660c-7836-4366-b178-9e9c1b7cd797.png)

**Comment by shadcn** [comment]
Place the images in the `static` folder. See https://www.gatsbyjs.com/docs/how-to/images-and-media/static-folder/

**Comment by deeplinked** [comment]
thanks a lot, that worked. you are awesome, every time replying swiftly :) closing the issue.
