### ISSUE TITLE
Can't use `flexDirection` with breakpoints

### ISSUE THREAD

**Issue by RishikeshDarandale** [reflexjs/reflexjs#90]
# Can't use `flexDirection` with breakpoints

Similar behaviour is observed from textAlign.

```jsx
<Flexbox
  flexDirection="column|row|row" ... >
  ...
</Flexbox>
```

Error:

> Type error: Type '"column|row"' is not assignable to type 'FlexDirectionProperty'

**Comment by arshad** [comment]
I see. Looks like we'll need to update the type for this. Any other properties with similar warnings?

**Comment by RishikeshDarandale** [comment]
Hey @arshad , thanks for the quick reply.

Here is one more, I will add more there once I see the errors!
- fontWeight="light"

Also, why below one is not translated to actual value?

```
<H2 fontSize="3xl"> </H2>  
```

PS: I am using preset!

**Comment by arshad** [comment]
Hmm I can't reproduce this. See example: https://csl9l.sse.codesandbox.io/basic

Codesandbox: https://codesandbox.io/s/goofy-swirles-csl9l?file=/content/pages/basic.mdx

Which preset are you using?

**Comment by arshad** [comment]
I wonder how we're going to fix this. If we use a mapped type with `string` then we'll probably lose suggestions for values like `column`, `row`..etc.

```ts
export type BoxProps<T> = {
  [P in keyof T]?: T[P] | string
}
```

**Comment by RishikeshDarandale** [comment]
```jsx
(JSX attribute) flexDirection?: FlexDirectionProperty
```
This is how the `flexDirection` type is, thus it would be either `column|row`.

Smae with `fontWeight` 

```
(JSX attribute) fontWeight?: FontWeightProperty
```

I can not have as below:

```
fontWeight="light"
```

Looks like we have use `sx = {{ }}`.

**Comment by RishikeshDarandale** [comment]
> Hmm I can't reproduce this. See example: https://csl9l.sse.codesandbox.io/basic
> 
> Codesandbox: https://codesandbox.io/s/goofy-swirles-csl9l?file=/content/pages/basic.mdx
> 
> Which preset are you using?

I am using `next.js` and having issues with replacement of attribute and sx attribute as well. I have referred this [one](https://reflexjs.org/blog/reflex-create-react-app) to configure. 
- step 1: create a next app
- step 2 as described above in document
- created a theme.ts as below:

```
import base from '@reflexjs/preset-base';

export default {
  preset: base,
  colors: {
    ...
  }
  ...
}
```
- _app.tsx as below

```
...

import { ThemeProvider } from 'theme-ui';
import theme from '../theme/theme';

export default function SearsHomeServices({
  Component,
  pageProps,
}: AppProps): JSX.Element {
  const apolloClient = useApollo(pageProps.initialApolloState);

  return (
    <ThemeProvider theme={theme}>
      <ApolloProvider client={apolloClient}>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </ApolloProvider>
    </ThemeProvider>
  );
}
```

**Comment by RishikeshDarandale** [comment]
> > Hmm I can't reproduce this. See example: https://csl9l.sse.codesandbox.io/basic
> > Codesandbox: https://codesandbox.io/s/goofy-swirles-csl9l?file=/content/pages/basic.mdx
> > Which preset are you using?
> 
> I am using `next.js` and having issues with replacement of attribute and sx attribute as well. I have referred this [one](https://reflexjs.org/blog/reflex-create-react-app) to configure.
> 
> * step 1: create a next app
> * step 2 as described above in document
> * created a theme.ts as below:
> 
> ```
> import base from '@reflexjs/preset-base';
> 
> export default {
>   preset: base,
>   colors: {
>     ...
>   }
>   ...
> }
> ```
> 
> * _app.tsx as below
> 
> ```
> ...
> 
> import { ThemeProvider } from 'theme-ui';
> import theme from '../theme/theme';
> 
> export default function SearsHomeServices({
>   Component,
>   pageProps,
> }: AppProps): JSX.Element {
>   const apolloClient = useApollo(pageProps.initialApolloState);
> 
>   return (
>     <ThemeProvider theme={theme}>
>       <ApolloProvider client={apolloClient}>
>         <Layout>
>           <Component {...pageProps} />
>         </Layout>
>       </ApolloProvider>
>     </ThemeProvider>
>   );
> }
> ```

I think the issue is `theme.ts`

```
import base from '@reflexjs/preset-base';
 
 export default {
   ...base,
   colors: {
     ...
   }
   ...
 }
```

**Comment by arshad** [comment]
Sure. Thank you.

**Comment by arshad** [comment]
I think for now we could solve the TS type using `string` (which would remove the suggestions) but we can later fix this when template literal types are supported.

**Comment by ttayehh24** [comment]
@RishikeshDarandale @arshad 
So I currently have an issue with AddToCalendar.tsx component.  When I'm trying to import styling components below to style the Add to Calendar link from reflexjs I'm getting errors in the ci/circleci.  I'm noticing that the AddToCalendar.tsx isn't recognizing reflexjs for some odd reason.

TypeError: Cannot read property 'button' of null
TypeError: Cannot read property 'span' of null

`import { Button, Span } from '@reflexjs/ui';` 

If I import components from theme-ui as example below everything works fine and passes without any issues. 

`import { jsx, Text } from 'theme-ui';`

I was wondering if you can take a look at this issue otherwise the alternative that I'm aware of at this moment is I'm going to  style the 'Add to Calender' link below with all inline-styling from theme-UI instead of reflexjs which works with no issues.

**Comment by arshad** [comment]
@ttayehh24 Hmm. This is failing on ci only?

**Comment by arshad** [comment]
@RishikeshDarandale ok to close this one?

**Comment by RishikeshDarandale** [comment]
yes @arshad
